name: Library Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Install go-junit-report
      run: go install github.com/jstemmer/go-junit-report@latest

    - name: Run tests
      run: go test -v ./... 2>&1 | tee test-results.log | go-junit-report > report.xml

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: report.xml
